language: ruby
rvm:
  - "2.1.4"

before_script:
  - psql -c "create database linkinglaw_production;" -U postgres

deploy:
  provider: heroku
  api_key: "7c03744a91dcaea828329dfb5d45246a727b412f"
  app: linkinglaw
  run: "rake db:migrate"
