default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5
  template: template0

development:
  <<: *default
  database: "<%= ENV['DATABASE_DEVELOPMENT'] %>"
  username: "<%= ENV['DATABASE_USER_DEVELOPMENT'] %>"
  password: "<%= ENV['DATABASE_PASSWORD_DEVELOPMENT'] %>"

test: &test
  <<: *default
  database: "linkinglaw_test"
  username: postgres
  password: "Foadih!01"

production:
  <<: *default
  database: "<%= ENV['DATABASE_PRODUCTION'] %>"
  username: "<%= ENV['DATABASE_USER_PRODUCTION'] %>"
  password: "<%= ENV['DATABASE_PASSWORD_PRODUCTION'] %>"

cucumber:
  <<: *test
