# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["MAILER_PASSWORD_DEV"] %>
  email_provider_username: <%= ENV["MAILER_USERNAME_DEV"] %>
  email_provider_password: <%= ENV["MAILER_PASSWORD_DEV"] %>
  email_address: <%= ENV["MAILER_ADDRESS_DEV"]%>
  domain_name: <%= ENV["DOMAIN_NAME_DEV"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE_DEV"] %>

test:
  domain_name: linkinglaw.nl
  secret_key_base: e07a95aa9ffac58ff906907ae149666ae689615093bdc975c0b8319e6e6c64b3042040c74ca77bdf5b6f7563b56e785cdc251d3243b71e14bc233d0d0878b12d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username: <%= ENV["MAILER_USERNAME_PRD"] %>
  email_provider_apikey: <%= ENV["MAILER_APIKEY_PRD"] %> 
  email_address: <%= ENV["MAILER_ADDRESS_PRD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
